In [54]:
import pandas as pd

melbourne = pd.read_csv("temperature_Melbourne_celsius.csv", delimiter=";")
oslo = pd.read_csv("temperature_Oslo_celsius.csv", delimiter=";")
quito = pd.read_csv("temperature_Quito_celsius.csv", delimiter=";")

# Ejercicio 1A

In [55]:
# Asegurar que la columna de temperatura sea la correcta
columna_temperatura = "AvgTemperature"  # Cambia esto según el nombre de la columna en los archivos

# Calcular la media y desviación estándar
media_melbourne = melbourne[columna_temperatura].mean()
media_oslo = oslo[columna_temperatura].mean()
media_quito = quito[columna_temperatura].mean()

desvio_melbourne = melbourne[columna_temperatura].std()
desvio_oslo = oslo[columna_temperatura].std()
desvio_quito = quito[columna_temperatura].std()

# Mostrar los resultados con formato mejorado
print(f"Media de Melbourne: {media_melbourne:.2f}°C")
print(f"Media de Oslo: {media_oslo:.2f}°C")
print(f"Media de Quito: {media_quito:.2f}°C")

print(f"Desvío estándar de Melbourne: {desvio_melbourne:.2f}°C")
print(f"Desvío estándar de Oslo: {desvio_oslo:.2f}°C")
print(f"Desvío estándar de Quito: {desvio_quito:.2f}°C")

Media de Melbourne: 17.53°C
Media de Oslo: 4.61°C
Media de Quito: 13.60°C
Desvío estándar de Melbourne: 6.48°C
Desvío estándar de Oslo: 9.46°C
Desvío estándar de Quito: 1.30°C


### 1 -B

In [56]:
from scipy.signal import correlate
import numpy as np

x = oslo[columna_temperatura].values
y = melbourne[columna_temperatura].values

corr = correlate(x, y, mode='full')
print(f"Correlación entre Oslo y Melbourne: {corr.max():.2f}")

x = oslo[columna_temperatura].values
y = quito[columna_temperatura].values

corr = correlate(x, y, mode='full')
print(f"Correlación entre Oslo y Quito: {corr.max():.2f}")

x = quito[columna_temperatura].values
y = melbourne[columna_temperatura].values

corr = correlate(x, y, mode='full')
print(f"Correlación entre quito y Melbourne: {corr.max():.2f}")


Correlación entre Oslo y Melbourne: 624455.00
Correlación entre Oslo y Quito: 376918.00
Correlación entre quito y Melbourne: 1393015.00


Analizando los resultados obtenidos observamos que entre oslo y cualquir otra ciudad no hay tremperatura climatica similar, en cambio entre Quito y Merburne hay una mayor correlacion por lo que hay una similitud, lo cual tiene sentido observando las medias.

## 2.
### Considerando los valores de temperatura t que componen cada señal Si, construir una nueva señal Ti  compuesta por una secuencia de símbolos discretos F, T o C, definidos según: 

In [ ]:

def clasificar_temperatura(t):
    if t < 11:
        return 'F'
    elif t < 19:
        return 'T'
    else:
        return 'C'

for df in [oslo, quito, melbourne]:
    df['Clima'] = df[columna_temperatura].apply(clasificar_temperatura)



#### Parte 1

In [ ]:
def contar_climas(df):
    conteo = df['Clima'].value_counts()
    f =  conteo.get('F', 0) 
    t = conteo.get('T', 0)
    c =  conteo.get('C', 0)
    return f, t, c

f_oslo, t_oslo, c_oslo = contar_climas(oslo)
f_quito, t_quito, c_quito = contar_climas(quito)
f_melbourne, t_melbourne, c_melbourne = contar_climas(melbourne)

def contar_transiciones(df, origen):
    """
    Cuenta cuántas veces después de 'origen' aparece cada letra ('F', 'T', 'C') en la columna 'Clima' del DataFrame.
    Retorna un diccionario con el conteo de transiciones.
    """
    clima = df['Clima'].values
    transiciones = {'F': 0, 'T': 0, 'C': 0}
    for i in range(len(clima) - 1):
        if clima[i] == origen:
            siguiente = clima[i + 1]
            if siguiente in transiciones:
                transiciones[siguiente] += 1
    return transiciones

def distribucion_probabilidad(df,f, t, c):
    matriz = [[0,0,0],
            [0,0,0],
            [0,0,0]]
    i = 0
    for l in ['F', 'T', 'C']:
        transiciones = contar_transiciones(df, l)
        matriz[i][0] = round(transiciones['F']/f, 3)
        matriz[i][1] = round(transiciones['T']/t, 3)
        matriz[i][2] = round(transiciones['C']/c, 3)
        i += 1
    return np.array(matriz)   

distribucion_oslo = distribucion_probabilidad(oslo, f_oslo, t_oslo, c_oslo)
distribucion_quito = distribucion_probabilidad(quito, f_quito, t_quito, c_quito)
distribucion_melbourne = distribucion_probabilidad(melbourne, f_melbourne, t_melbourne, c_melbourne)

print("Distribución de probabilidad de Oslo:")
print(distribucion_oslo)
print("--------------------------------------------")
print("Distribución de probabilidad de Quito:")
print(distribucion_quito)
print("--------------------------------------------")
print("Distribución de probabilidad de Melbourne:")
print(distribucion_melbourne)


Distribución de probabilidad de Oslo:
[[0.959 0.099 0.   ]
 [0.041 0.865 0.296]
 [0.    0.035 0.704]]
--------------------------------------------
Distribución de probabilidad de Quito:
[[0.054 0.006 0.   ]
 [0.946 0.993 1.   ]
 [0.    0.001 0.   ]]
--------------------------------------------
Distribución de probabilidad de Melbourne:
[[0.47  0.033 0.003]
 [0.495 0.836 0.144]
 [0.035 0.131 0.853]]


#### Parte 2

In [107]:
import numpy as np

def distribucion_probabilistica_estacionaria(matriz, origen, tolerance=100, atol=1e-6):
    res = np.dot(origen, matriz)
    
    while not np.allclose(res, origen, atol=atol) and tolerance > 0:
        origen = res
        res = np.dot(origen, matriz)
        tolerance -= 1

    return res

distribucion_estacionaria_oslo = distribucion_probabilistica_estacionaria(distribucion_oslo, [0, 1, 0])
print(distribucion_estacionaria_oslo)


[0.27439542 0.27251125 0.27277144]
